### ISSUE TITLE
Using own data, how to convert?

### ISSUE THREAD

**Issue by antithing** [ZJUCVG/EIBA#1]
Hi, and thank you for making this code available. I am trying to get my own data in and run it live, could you clear up a question for me?

to push data in, I use:

```
void BAInterface::PushKeyframeFeatures(const EIBA::Camera &initial_camera,
                                       const std::vector<float> &initial_depths,
                                       const std::vector<Feature> &source_features,
                                       const std::vector<Measurement> &measured_features)
```

What I have is:

the camera pose.
3d points, which are:
3d position as Eigen::Vector3d;
A std::vector of 'Observations', each made up of a keyframe and Point2d.

How can convert this data to what is needed by EIBA?
How can I get the inverse depth that is needed?

Any help is much appreciated. 
Thanks!

**Comment by ZJUCVG** [comment]
EIBA use inverse depth parameterization for 3D points and do not directly optimize 3D position.  All the feature points are parameterized in the form of inverse depth and the corresponding camera location from which they were first observed. You can decompose 3D position into inverse depth at the first observation and its corresponding camera pose.

The inverse depth is obtained by a depth camera(e.g. Asus Xtion or Kinect).
